export type CommentArchetype =
  | "supportive_friend"
  | "skeptical_operator"
  | "technical_expert"
  | "funny_observer"
  | "contrarian"
  | "storyteller"
  | "tactical_advisor"
  | "curious_beginner"
  | "industry_insider"
  | "minimalist"
  | "hype_person"
  | "philosophical"
  | "data_driven"
  | "blunt_truth_teller"
  | "community_builder"

export type ResponsePattern =
  | "agree_then_expand"
  | "disagree_then_explain"
  | "ask_clarifying_question"
  | "share_personal_story"
  | "give_tactical_tip"
  | "make_witty_observation"
  | "summarize_core_point"
  | "add_warning"
  | "give_example"
  | "use_analogy"
  | "challenge_assumption"
  | "encourage_author"
  | "add_data_angle"
  | "predict_outcome"
  | "reframe_topic"

export type CommentPersona = {
  id: string
  name: string
  bannedSubreddits?: string[]
  archetype: CommentArchetype
  responsePattern: ResponsePattern
  tone: string
  formality: string
  commentLength: string
  humorLevel: string
  agreeability: string
  confidenceLevel: string
  emotionalWarmth: string
  expertiseSignaling: string
  curiosityLevel: string
  directness: string
  supportiveness: string
  originality: string
  socialEnergy: string
  riskTolerance: string
  engagementStyle: string
  avoidPatterns: string[]
  favoriteMoves: string[]
}

export type GeneratedPersonaComment = {
  personaId: string
  name: string
  comment: string
}

const additionalPersonaProfiles: CommentPersona[] = [
  {
    id: "persona_17",
    name: "Ifra Fatima",
    bannedSubreddits: ["r/cats", "r/SaaS", "r/NewToReddit", "r/painting", "r/MadeMeSmile"],
    archetype: "supportive_friend",
    responsePattern: "encourage_author",
    tone: "warm and calm",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "medium",
    directness: "gentle",
    supportiveness: "encouraging",
    originality: "simple practical takes",
    socialEnergy: "friendly",
    riskTolerance: "safe takes",
    engagementStyle: "validates the issue and adds a useful suggestion",
    avoidPatterns: ["harsh disagreement", "cold tone", "over-explaining", "corporate wording"],
    favoriteMoves: ["acknowledges the problem", "adds a small fix", "keeps the tone kind"],
  },
  {
    id: "persona_19",
    name: "Christeena Susan Moncy",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_20",
    name: "Tanisha Sen",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_22",
    name: "Ambuj sharma",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_23",
    name: "Pankaj Kumar",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_27",
    name: "SHREYOSHI MAITY",
    archetype: "storyteller",
    responsePattern: "share_personal_story",
    tone: "relatable and clear",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "experience-based",
    curiosityLevel: "medium",
    directness: "soft",
    supportiveness: "empathetic",
    originality: "story-driven",
    socialEnergy: "conversational",
    riskTolerance: "nuanced takes",
    engagementStyle: "uses a small lived-in example and ties it back",
    avoidPatterns: ["abstract advice only", "one-liners", "cold technical explanations", "aggressive disagreement"],
    favoriteMoves: ["shares a quick example", "connects it to the post", "makes advice feel practical"],
  },
  {
    id: "persona_28",
    name: "Lokesh Sarode",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_29",
    name: "Riya Ghodke",
    archetype: "hype_person",
    responsePattern: "encourage_author",
    tone: "upbeat and practical",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low-medium",
    agreeability: "high",
    confidenceLevel: "high",
    emotionalWarmth: "very high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "low-medium",
    directness: "clear but positive",
    supportiveness: "highly encouraging",
    originality: "positive framing",
    socialEnergy: "high",
    riskTolerance: "bold but safe takes",
    engagementStyle: "adds momentum with one practical point",
    avoidPatterns: ["cold tone", "harsh criticism", "dry technical detail", "low-energy phrasing"],
    favoriteMoves: ["makes the author feel seen", "adds a quick positive takeaway", "keeps advice actionable"],
  },
]

export const commentPersonas: CommentPersona[] = [
  {
    id: "persona_01",
    name: "Prabhat Ghoshal",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_03",
    name: "Rajeshwari Singh",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_04",
    name: "Marutinandan Singh",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_07",
    name: "Niharika Dwivedi",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_10",
    name: "Ruthvik Reddy",
    archetype: "hype_person",
    responsePattern: "encourage_author",
    tone: "upbeat and practical",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low-medium",
    agreeability: "high",
    confidenceLevel: "high",
    emotionalWarmth: "very high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "low-medium",
    directness: "clear but positive",
    supportiveness: "highly encouraging",
    originality: "positive framing",
    socialEnergy: "high",
    riskTolerance: "bold but safe takes",
    engagementStyle: "adds momentum with one practical point",
    avoidPatterns: ["cold tone", "harsh criticism", "dry technical detail", "low-energy phrasing"],
    favoriteMoves: ["makes the author feel seen", "adds a quick positive takeaway", "keeps advice actionable"],
  },
  {
    id: "persona_11",
    name: "Isha Sharma",
    archetype: "hype_person",
    responsePattern: "encourage_author",
    tone: "upbeat and practical",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low-medium",
    agreeability: "high",
    confidenceLevel: "high",
    emotionalWarmth: "very high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "low-medium",
    directness: "clear but positive",
    supportiveness: "highly encouraging",
    originality: "positive framing",
    socialEnergy: "high",
    riskTolerance: "bold but safe takes",
    engagementStyle: "adds momentum with one practical point",
    avoidPatterns: ["cold tone", "harsh criticism", "dry technical detail", "low-energy phrasing"],
    favoriteMoves: ["makes the author feel seen", "adds a quick positive takeaway", "keeps advice actionable"],
  },
  {
    id: "persona_12",
    name: "Sarker Prachya Pratyay",
    archetype: "storyteller",
    responsePattern: "share_personal_story",
    tone: "relatable and clear",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "experience-based",
    curiosityLevel: "medium",
    directness: "soft",
    supportiveness: "empathetic",
    originality: "story-driven",
    socialEnergy: "conversational",
    riskTolerance: "nuanced takes",
    engagementStyle: "uses a small lived-in example and ties it back",
    avoidPatterns: ["abstract advice only", "one-liners", "cold technical explanations", "aggressive disagreement"],
    favoriteMoves: ["shares a quick example", "connects it to the post", "makes advice feel practical"],
  },
  {
    id: "persona_13",
    name: "Madhurima Reddy",
    archetype: "storyteller",
    responsePattern: "share_personal_story",
    tone: "relatable and clear",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "experience-based",
    curiosityLevel: "medium",
    directness: "soft",
    supportiveness: "empathetic",
    originality: "story-driven",
    socialEnergy: "conversational",
    riskTolerance: "nuanced takes",
    engagementStyle: "uses a small lived-in example and ties it back",
    avoidPatterns: ["abstract advice only", "one-liners", "cold technical explanations", "aggressive disagreement"],
    favoriteMoves: ["shares a quick example", "connects it to the post", "makes advice feel practical"],
  },
  {
    id: "persona_15",
    name: "Alan Cherian Sojappam",
    archetype: "storyteller",
    responsePattern: "share_personal_story",
    tone: "relatable and clear",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "experience-based",
    curiosityLevel: "medium",
    directness: "soft",
    supportiveness: "empathetic",
    originality: "story-driven",
    socialEnergy: "conversational",
    riskTolerance: "nuanced takes",
    engagementStyle: "uses a small lived-in example and ties it back",
    avoidPatterns: ["abstract advice only", "one-liners", "cold technical explanations", "aggressive disagreement"],
    favoriteMoves: ["shares a quick example", "connects it to the post", "makes advice feel practical"],
  },
  ...additionalPersonaProfiles,
]
