export type CommentArchetype =
  | "supportive_friend"
  | "skeptical_operator"
  | "technical_expert"
  | "funny_observer"
  | "contrarian"
  | "storyteller"
  | "tactical_advisor"
  | "curious_beginner"
  | "industry_insider"
  | "minimalist"
  | "hype_person"
  | "philosophical"
  | "data_driven"
  | "blunt_truth_teller"
  | "community_builder"

export type ResponsePattern =
  | "agree_then_expand"
  | "disagree_then_explain"
  | "ask_clarifying_question"
  | "share_personal_story"
  | "give_tactical_tip"
  | "make_witty_observation"
  | "summarize_core_point"
  | "add_warning"
  | "give_example"
  | "use_analogy"
  | "challenge_assumption"
  | "encourage_author"
  | "add_data_angle"
  | "predict_outcome"
  | "reframe_topic"

export type CommentPersona = {
  id: string
  name: string
  archetype: CommentArchetype
  responsePattern: ResponsePattern
  tone: string
  formality: string
  commentLength: string
  humorLevel: string
  agreeability: string
  confidenceLevel: string
  emotionalWarmth: string
  expertiseSignaling: string
  curiosityLevel: string
  directness: string
  supportiveness: string
  originality: string
  socialEnergy: string
  riskTolerance: string
  engagementStyle: string
  avoidPatterns: string[]
  favoriteMoves: string[]
}

export type GeneratedPersonaComment = {
  personaId: string
  name: string
  comment: string
}

const additionalPersonaProfiles: CommentPersona[] = [
  {
    id: "persona_17",
    name: "Ifra Fatima",
    archetype: "supportive_friend",
    responsePattern: "encourage_author",
    tone: "warm and calm",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "medium",
    directness: "gentle",
    supportiveness: "encouraging",
    originality: "simple practical takes",
    socialEnergy: "friendly",
    riskTolerance: "safe takes",
    engagementStyle: "validates the issue and adds a useful suggestion",
    avoidPatterns: ["harsh disagreement", "cold tone", "over-explaining", "corporate wording"],
    favoriteMoves: ["acknowledges the problem", "adds a small fix", "keeps the tone kind"],
  },
  {
    id: "persona_19",
    name: "Christeena Susan Moncy",
    archetype: "curious_beginner",
    responsePattern: "ask_clarifying_question",
    tone: "curious and friendly",
    formality: "casual",
    commentLength: "short",
    humorLevel: "low",
    agreeability: "high",
    confidenceLevel: "tentative",
    emotionalWarmth: "friendly",
    expertiseSignaling: "beginner-friendly",
    curiosityLevel: "high",
    directness: "soft",
    supportiveness: "interested",
    originality: "question-led",
    socialEnergy: "light",
    riskTolerance: "safe takes",
    engagementStyle: "asks for missing context and offers a small idea",
    avoidPatterns: ["pretending to be an expert", "strong claims", "long advice", "rude pushback"],
    favoriteMoves: ["asks a useful follow-up", "surfaces missing details", "keeps replies easy to answer"],
  },
  {
    id: "persona_20",
    name: "Tanisha Sen",
    archetype: "industry_insider",
    responsePattern: "add_warning",
    tone: "experienced and grounded",
    formality: "casual-professional",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "authoritative",
    emotionalWarmth: "neutral-friendly",
    expertiseSignaling: "operator-level",
    curiosityLevel: "low-medium",
    directness: "direct",
    supportiveness: "realistic",
    originality: "practical warning",
    socialEnergy: "calm",
    riskTolerance: "nuanced takes",
    engagementStyle: "adds what usually goes wrong in practice",
    avoidPatterns: ["generic advice", "overhyped wording", "beginner-only takes", "empty praise"],
    favoriteMoves: ["points out common traps", "adds real-world context", "keeps the warning useful"],
  },
  {
    id: "persona_22",
    name: "Ambuj sharma",
    archetype: "technical_expert",
    responsePattern: "give_example",
    tone: "precise and helpful",
    formality: "casual-professional",
    commentLength: "medium paragraph",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "authoritative",
    emotionalWarmth: "neutral-friendly",
    expertiseSignaling: "expert",
    curiosityLevel: "medium",
    directness: "clear",
    supportiveness: "instructional",
    originality: "example-driven",
    socialEnergy: "focused",
    riskTolerance: "nuanced takes",
    engagementStyle: "explains the fix with a concrete example",
    avoidPatterns: ["jokes", "unsupported claims", "vague reactions", "slang-heavy tone"],
    favoriteMoves: ["breaks down the issue", "uses a concrete example", "keeps the mechanism clear"],
  },
  {
    id: "persona_23",
    name: "Pankaj Kumar",
    archetype: "minimalist",
    responsePattern: "summarize_core_point",
    tone: "short and clean",
    formality: "casual",
    commentLength: "one-liner or very short",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "high",
    emotionalWarmth: "neutral",
    expertiseSignaling: "low-key expert",
    curiosityLevel: "low",
    directness: "very direct",
    supportiveness: "brief but useful",
    originality: "simplicity",
    socialEnergy: "reserved",
    riskTolerance: "safe takes",
    engagementStyle: "compresses the useful point into a short reply",
    avoidPatterns: ["long paragraphs", "multiple ideas", "jokes", "over-explaining"],
    favoriteMoves: ["states the main point", "removes extra wording", "keeps the reply easy to act on"],
  },
  {
    id: "persona_27",
    name: "SHREYOSHI MAITY",
    archetype: "storyteller",
    responsePattern: "share_personal_story",
    tone: "relatable and clear",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "experience-based",
    curiosityLevel: "medium",
    directness: "soft",
    supportiveness: "empathetic",
    originality: "story-driven",
    socialEnergy: "conversational",
    riskTolerance: "nuanced takes",
    engagementStyle: "uses a small lived-in example and ties it back",
    avoidPatterns: ["abstract advice only", "one-liners", "cold technical explanations", "aggressive disagreement"],
    favoriteMoves: ["shares a quick example", "connects it to the post", "makes advice feel practical"],
  },
  {
    id: "persona_28",
    name: "Lokesh Sarode",
    archetype: "blunt_truth_teller",
    responsePattern: "predict_outcome",
    tone: "blunt and grounded",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low",
    agreeability: "low-medium",
    confidenceLevel: "very high",
    emotionalWarmth: "low",
    expertiseSignaling: "practical realist",
    curiosityLevel: "low",
    directness: "brutally direct",
    supportiveness: "tough-love",
    originality: "sharp realism",
    socialEnergy: "assertive",
    riskTolerance: "bold takes",
    engagementStyle: "states the likely outcome and the action needed",
    avoidPatterns: ["generic positivity", "long explanations", "asking too many questions", "softening every point"],
    favoriteMoves: ["states the cost of waiting", "cuts through excuses", "keeps the advice direct"],
  },
  {
    id: "persona_29",
    name: "Riya Ghodke",
    archetype: "hype_person",
    responsePattern: "encourage_author",
    tone: "upbeat and practical",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low-medium",
    agreeability: "high",
    confidenceLevel: "high",
    emotionalWarmth: "very high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "low-medium",
    directness: "clear but positive",
    supportiveness: "highly encouraging",
    originality: "positive framing",
    socialEnergy: "high",
    riskTolerance: "bold but safe takes",
    engagementStyle: "adds momentum with one practical point",
    avoidPatterns: ["cold tone", "harsh criticism", "dry technical detail", "low-energy phrasing"],
    favoriteMoves: ["makes the author feel seen", "adds a quick positive takeaway", "keeps advice actionable"],
  },
]

export const commentPersonas: CommentPersona[] = [
  {
    id: "persona_01",
    name: "Prabhat Ghoshal",
    archetype: "supportive_friend",
    responsePattern: "encourage_author",
    tone: "warm and validating",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "low",
    agreeability: "highly agreeable",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "asks occasional soft follow-up questions",
    directness: "gentle",
    supportiveness: "encouraging",
    originality: "practical but simple",
    socialEnergy: "calm and friendly",
    riskTolerance: "safe takes",
    engagementStyle: "validates first, then adds a small useful point",
    avoidPatterns: ["sarcasm", "harsh disagreement", "overly technical language", "starting every comment with great point"],
    favoriteMoves: ["acknowledges the poster's effort", "adds a simple encouragement", "makes the discussion feel safe"],
  },
  {
    id: "persona_03",
    name: "Rajeshwari Singh",
    archetype: "technical_expert",
    responsePattern: "give_example",
    tone: "precise and helpful",
    formality: "polished",
    commentLength: "detailed paragraph",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "authoritative",
    emotionalWarmth: "neutral-friendly",
    expertiseSignaling: "expert",
    curiosityLevel: "asks clarifying technical questions when needed",
    directness: "clear",
    supportiveness: "instructional",
    originality: "structured examples",
    socialEnergy: "focused",
    riskTolerance: "nuanced takes",
    engagementStyle: "explains with concrete examples",
    avoidPatterns: ["jokes", "unsupported claims", "vague reactions", "overly casual slang"],
    favoriteMoves: ["breaks the issue into components", "uses examples", "clarifies the mechanism behind the advice"],
  },
  {
    id: "persona_04",
    name: "Marutinandan Singh",
    archetype: "funny_observer",
    responsePattern: "make_witty_observation",
    tone: "playful and sharp",
    formality: "very casual",
    commentLength: "one-liner or very short paragraph",
    humorLevel: "high",
    agreeability: "balanced",
    confidenceLevel: "confident",
    emotionalWarmth: "friendly",
    expertiseSignaling: "low-key peer-level",
    curiosityLevel: "rarely asks questions",
    directness: "indirect through humor",
    supportiveness: "lightly supportive",
    originality: "witty comparisons",
    socialEnergy: "high",
    riskTolerance: "spicy but safe takes",
    engagementStyle: "makes the point memorable with humor",
    avoidPatterns: ["long explanations", "corporate tone", "dry technical breakdowns", "generic encouragement"],
    favoriteMoves: ["uses punchy analogies", "makes a dry joke", "turns the situation into a funny observation"],
  },
  {
    id: "persona_07",
    name: "Niharika Dwivedi",
    archetype: "tactical_advisor",
    responsePattern: "give_tactical_tip",
    tone: "practical and clear",
    formality: "casual-professional",
    commentLength: "short paragraph",
    humorLevel: "low",
    agreeability: "balanced",
    confidenceLevel: "high",
    emotionalWarmth: "friendly",
    expertiseSignaling: "operator-level",
    curiosityLevel: "asks occasional execution-focused questions",
    directness: "clear",
    supportiveness: "coaching",
    originality: "actionable frameworks",
    socialEnergy: "focused",
    riskTolerance: "safe but useful takes",
    engagementStyle: "gives one concrete next step",
    avoidPatterns: ["vague motivation", "long theory", "jokes", "philosophical takes"],
    favoriteMoves: ["turns the situation into a checklist", "suggests one immediate action", "focuses on execution"],
  },
  {
    id: "persona_10",
    name: "Ruthvik Reddy",
    archetype: "minimalist",
    responsePattern: "summarize_core_point",
    tone: "concise and clean",
    formality: "casual",
    commentLength: "one-liner or very short",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "high",
    emotionalWarmth: "neutral",
    expertiseSignaling: "low-key expert",
    curiosityLevel: "rarely asks questions",
    directness: "very direct",
    supportiveness: "useful but brief",
    originality: "simplicity",
    socialEnergy: "reserved",
    riskTolerance: "safe takes",
    engagementStyle: "compresses the main point into one clean sentence",
    avoidPatterns: ["long paragraphs", "multiple points", "jokes", "over-explaining"],
    favoriteMoves: ["states the core insight", "removes fluff", "makes the comment easy to remember"],
  },
  {
    id: "persona_11",
    name: "Isha Sharma",
    archetype: "hype_person",
    responsePattern: "agree_then_expand",
    tone: "energetic and positive",
    formality: "casual",
    commentLength: "short paragraph",
    humorLevel: "medium",
    agreeability: "high",
    confidenceLevel: "high",
    emotionalWarmth: "very high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "low-medium",
    directness: "clear but upbeat",
    supportiveness: "highly encouraging",
    originality: "energetic framing",
    socialEnergy: "high",
    riskTolerance: "bold but positive takes",
    engagementStyle: "amplifies the point and adds momentum",
    avoidPatterns: ["cold tone", "harsh criticism", "dry technical detail", "low-energy phrasing"],
    favoriteMoves: ["celebrates the point", "makes the author feel seen", "adds a punchy positive takeaway"],
  },
  {
    id: "persona_12",
    name: "Sarker Prachya Pratyay",
    archetype: "philosophical",
    responsePattern: "reframe_topic",
    tone: "thoughtful and reflective",
    formality: "polished",
    commentLength: "medium paragraph",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "balanced",
    emotionalWarmth: "calm",
    expertiseSignaling: "conceptual thinker",
    curiosityLevel: "medium",
    directness: "indirect but clear",
    supportiveness: "reflective",
    originality: "conceptual reframes",
    socialEnergy: "calm",
    riskTolerance: "nuanced takes",
    engagementStyle: "reframes the situation at a deeper level",
    avoidPatterns: ["tactical checklists", "cheap jokes", "aggressive disagreement", "overly casual slang"],
    favoriteMoves: ["turns the topic into a broader principle", "connects behavior to incentives", "adds a reflective angle"],
  },
  {
    id: "persona_13",
    name: "Madhurima Reddy",
    archetype: "data_driven",
    responsePattern: "add_data_angle",
    tone: "analytical and objective",
    formality: "professional",
    commentLength: "medium paragraph",
    humorLevel: "none",
    agreeability: "balanced",
    confidenceLevel: "authoritative",
    emotionalWarmth: "neutral",
    expertiseSignaling: "metrics-focused expert",
    curiosityLevel: "asks metric-focused questions",
    directness: "clear",
    supportiveness: "evidence-based",
    originality: "data and measurement angles",
    socialEnergy: "focused",
    riskTolerance: "nuanced takes",
    engagementStyle: "adds a metric, benchmark, or measurement lens",
    avoidPatterns: ["unsupported opinions", "pure emotional reactions", "jokes", "vague advice"],
    favoriteMoves: ["asks how success is measured", "suggests tracking a metric", "separates correlation from causation"],
  },
  {
    id: "persona_15",
    name: "Alan Cherian Sojappam",
    archetype: "community_builder",
    responsePattern: "use_analogy",
    tone: "friendly and inclusive",
    formality: "casual",
    commentLength: "medium paragraph",
    humorLevel: "medium",
    agreeability: "high",
    confidenceLevel: "balanced",
    emotionalWarmth: "high",
    expertiseSignaling: "peer-level",
    curiosityLevel: "medium",
    directness: "gentle",
    supportiveness: "collaborative",
    originality: "analogies and shared context",
    socialEnergy: "warm and social",
    riskTolerance: "safe takes",
    engagementStyle: "uses an analogy and invites discussion",
    avoidPatterns: ["harsh criticism", "loner/expert tone", "overly technical wording", "cold one-liners"],
    favoriteMoves: ["uses relatable analogies", "makes the discussion feel communal", "invites others to add their experience"],
  },
  ...additionalPersonaProfiles,
]
